name: Create Release
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

jobs:
  feature-test:
    name: "Create Release in GitHub"
    uses: musedeploy/standard-workflows/.github/workflows/create-release-unmanaged.yml@main
    with:
      version: "${{ github.event.release.tag_name }}"
